### ISSUE TITLE
Setting path variable

### ISSUE THREAD

**Issue by djpetifo** [LaunchCodeEducation/java-web-development#104]
In the java introduction and setup chapter, I tried to set path for the JDK using the method supplied in the chapter and it did not work. Alternatively after setting the PATH (all uppercase) I was able to get run my helloworld app. Is this instruction supposed to be case sensitive? If so would it be possible to change the instruction for clarity?

After doing some research I also saw that you can use setx to set the path permanently and setx /M to set it for all users on a particular machine. I haven't tried those as I just set the path manually with the GUI after I had to restart.

**Comment by gildedgardenia** [comment]
Thanks so much for your feedback! I am closing this issue as the textbook has been updated.
