### ISSUE TITLE
[Copy/Edit] Java version refresh (Java 13 deprecated).

### ISSUE THREAD

**Issue by jimflores5** [LaunchCodeEducation/java-web-development#115]
From an instructor:
"Heads up that the Java materials need a refresh. Everything tells students to use select Java 13 in the Spring Boot instructions, but Spring starter only offers 15, 11, and 8.  I suspect they'll also only support 15 until March when 16 is released."

**Comment by CarlyLanglois** [comment]
closing this, all materials are using java 11 now
