### ISSUE TITLE
[Copy/Edit] More Java version inconsistencies.

### ISSUE THREAD

**Issue by jimflores5** [LaunchCodeEducation/java-web-development#119]
## From an instructor:

Hi everyone! If you run into an issue where you can't import to use any of the validation annotations and you're using Java 15, within your `build.gradle` file, add the line implementation `org.springframework.boot:spring-boot-starter-validation` and it will fix it. 

Turns out they stopped including the validation library in spring-boot-starter-web not too long ago.

To be clear, you should NOT have to do this on any code you clone from GitHub for this course or any of your graded assignments- this will only be projects you create from `start.spring.io`

**Comment by CarlyLanglois** [comment]
also resolved by using java 11 so closing
