### ISSUE TITLE
[Update] GIS article referenced in ORM chapter will no longer be maintained.

### ISSUE THREAD

**Issue by jimflores5** [LaunchCodeEducation/java-web-development#132]
## Book link

https://education.launchcode.org/java-web-development/chapters/orm-part1/background.html#key-takeaways

## Issue

Section 17.1.1.3 links to an article in the gis-devops repo that will no longer be maintained.  The link works for now, but we should think about adding the document to the Java book itself.

## Screenshot

![Screen Shot 2021-03-10 at 1 40 32 PM](https://user-images.githubusercontent.com/31870126/110695217-35fd8880-81af-11eb-9aed-9e6e963118f2.png)

**Comment by CarlyLanglois** [comment]
corrected
