### ISSUE TITLE
[Clarification] Inconsistent versions given for Spring Boot installation.

### ISSUE THREAD

**Issue by jimflores5** [LaunchCodeEducation/java-web-development#143]
**Excerpts from student Slack conversation**:
"Does anyone know which version of Spring Boot we should be using? Video and text say 2.2, but I'm only seeing newer versions."

"Also, it doesn't allow us to use java 15 like the directions say, so should we go with java 11? The options are 8, 11, and 16.

"I think they mean 2.4.5, but who knows? The video gives one set of instructions. The book gives another set. Neither are apparently correct given the options available in the Springboot Initializr or IntelliJ."

Slack conversation link (5/17/2021): https://jan2021-lc101.slack.com/archives/C01JNPWALPJ/p1621020549275800

**Comment by CarlyLanglois** [comment]
resolved with recent merge
