### ISSUE TITLE
[Clairfication] Windows installation instructions for MySQL Workbench.

### ISSUE THREAD

**Issue by jimflores5** [LaunchCodeEducation/java-web-development#75]
Permalink:

https://education.launchcode.org/java-web-development/appendices/sql-install.html#windows-users

Description:

1) During installation, if a student clicks "Next" rather than "Execute", no server is opened, and this causes issues.
2) After clicking "Execute" in the full installation package, some Windows users are receiving warnings during the "Check" phase.  The errors tell the users to install Python and Visual Studio.
3) In some cases, all of the buttons except "Cancel" are greyed out, which causes confusion about whether the installation will be successful.

Screenshot(s):

![image(1)](https://user-images.githubusercontent.com/31870126/71984845-430b9a00-31ef-11ea-82a5-bb3663d7be27.png)

![image](https://user-images.githubusercontent.com/31870126/71984753-18b9dc80-31ef-11ea-8cf6-b9c9aa39e10f.png)

![image(2)](https://user-images.githubusercontent.com/31870126/71985286-efe61700-31ef-11ea-90c9-abde88570883.png)

**Comment by CarlyLanglois** [comment]
addressed in https://github.com/LaunchCodeEducation/java-web-development/pull/126
