### ISSUE TITLE
Short answer Questions in Canvas are too rigid?

### ISSUE THREAD

**Issue by CarlyLanglois** [LaunchCodeEducation/java-web-development#90]
See screenshot - correct answers don't get registered as correct. Not very high priority.

Screen Shot 2020-01-22 at 7.01.42 PM

**Comment by CarlyLanglois** [comment]
<img width="878" alt="Screen Shot 2020-01-22 at 7 01 42 PM" src="https://user-images.githubusercontent.com/20828430/73883901-60ea1000-482a-11ea-861e-343d68512337.png">

**Comment by jimflores5** [comment]
Revised Canvas concept check questions to be more flexible in accepted answers.
