### ISSUE TITLE
[Starter code fix] Fixes for assignment 4 starter code.

### ISSUE THREAD

**Issue by jimflores5** [LaunchCodeEducation/java-web-development#96]
Link:
https://github.com/LaunchCodeEducation/java-web-dev-techjobs-persistent

Descriptions:

1) From a student - In Assignment 4, ``skills/view.html``, it will throw errors unless you change the lines for ``skill.name``, ``skill.description``, and ``skill.jobs`` to "skills."  

For this issue, should we change ``skill`` to ``skills`` or find the original ``skills`` and convert it to ``skill``?

2) From another student - ...just noticed that on the search page, if you try to search for a term with ``All`` selected and the term is something in a skill (but not in any of your other fields), no jobs come back. I added the code highlighted below in ``JobData.java`` (scroll allll the way down) and it works now.

<img width="723" alt="Screen Shot 2020-01-30 at 7 57 02 PM" src="https://user-images.githubusercontent.com/31870126/73544814-9db7a080-43ff-11ea-84c3-b4dc66d134c2.png">

**Comment by CarlyLanglois** [comment]
closing this to discuss offline
